export const ancestries = {
    Avian: { name:"Avian", size: 1, traits: ["Flight", "Get the Flock Outta There", "Flock Tactics", "Gust"] },
    Cambion: { name:"Cambion", size: 1, traits: ['Bloodhunter', 'Infernal Resistance', 'Wrath', 'Fiendish Wings'] },
    Draken: { name:"Draken", size: 2, traits: ['Dragonfire', 'Dragon Scales', 'Inner Fire', 'Draconic Wings'] },
    Dwarf: { name:"Dwarf", size: 1, traits: ['Keep Moving Forward', 'Resilience', 'Unyielding', 'Sturdy'] },
    Elemental: { name:"Elemental", size: 1, traits: ['Energy Resistance', 'Energy Aura', 'Elemental Nova', 'Elemental Form'] },
    Elf: { name:"Elf", size: 1, traits: ['Elven Accuracy', 'Nature Step', 'Fast Movement', 'Fey Step'] },
    Gigan: { name:"Gigan", size: 2, traits: ['Big Equipment', 'Endure', 'Oversized Weapons', 'Giant Lineage'] },
    Gnome: { name:"Gnome", size: 1 / 2, traits: ['Instinctual Stealth', 'Fade Away', 'Tumble', 'Tinker Toy'] },
    Goblin: { name:"Goblin", size: 1 / 2, traits: ['Scurry', 'Swarm', 'Nimble Escape', 'Bite'] },
    Halfling: { name:"Halfling", size: 1 / 2, traits: ['Lucky', 'Nimble', 'Brave', 'Tumble'] },
    Human: { name:"Human", size: 1, traits: ['Strong Saves', 'Hang in There', 'Hearty', 'Adrenaline'] },
    Kobold: { name:"Kobold", size: 1 / 2, traits: ['Trap Array', 'Distract', 'Trapmaster', 'Evasive'] },
    Lycanthrope: { name:"Lycanthrope", size: 1, traits: ['Defender Strain', 'Pack Tactics', 'Sneaky Form', 'Travel Form'] },
    Machina: { name:"Machina", size: 1, traits: ['Mechanical Body', 'Armored', 'System Repair', 'Integrated Weapon'] },
    Orc: { name:"Orc", size: 2, traits: ['Second Wind', 'Rushdown', 'Furious', 'Work Out Routine'] },
}