export const ancestries = {
    Avian: { name:"Avian", size: 1, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Cambion: { name:"Cambion", size: 1, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Draken: { name:"Draken", size: 2, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Dwarf: { name:"Dwarf", size: 1, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Elementals: { name:"Elementals", size: 1, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Elf: { name:"Elf", size: 1, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Gigan: { name:"Gigan", size: 2, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Gnome: { name:"Gnome", size: 1 / 2, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Goblin: { name:"Goblin", size: 1 / 2, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Halfling: { name:"Halfling", size: 1 / 2, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Human: { name:"Human", size: 1, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Kobold: { name:"Kobold", size: 1 / 2, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Lycanthrope: { name:"Lycanthrope", size: 1, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Machina: { name:"Machina", size: 1, traits: [{ name: "traitName", effect: "traitEffect" }] },
    Orc: { name:"Orc", size: 2, traits: [{ name: "traitName", effect: "traitEffect" }] },
}