const weaponSlot = { 1: "[LIGHT]", 2: "[MAIN]", 3: "[HEAVY]", 11: "[LIGHT/LIGHT]", 21: ["MAIN/LIGHT"] }
const supportSlot = { 1: "[LIGHT]", 2: "[MAIN]", 3: "[HEAVY]" }

export const jobsData = {
  Aegis: { name: "Aegis", stats: { scope: 10, hp: 6, recoveries: 3, dodge: 6, speed: 4, stresscap: 7, memory: 7, adef: 10, mp: 5, saveTarget: 10 }, weapons: [weaponSlot[1], weaponSlot[2]], supports: [supportSlot[1], supportSlot[1]], traits: ["Abjurer's Ward", "Mana Transferral"], limitbreak: "Perfect Shield" },
  Alchemist: { name: "Alchemist", stats: { scope: 8, hp: 7, recoveries: 5, dodge: 7, speed: 5, stresscap: 6, memory: 5, adef: 8, mp: 3, saveTarget: 11 }, weapons: [weaponSlot[2]], supports: [supportSlot[1], supportSlot[2], supportSlot[2], supportSlot[2]], traits: ["Potion Belt", "Potion Injector", "Sanitizing Vapors"], limitbreak: "Philosopher's Stone" },
  Arsenal: { name: "Arsenal", stats: { scope: 5, hp: 10, recoveries: 5, dodge: 8, speed: 5, stresscap: 5, memory: 5, adef: 6, mp: 3, saveTarget: 10 }, weapons: [weaponSlot[2], weaponSlot[2], weaponSlot[3]], supports: [supportSlot[1], supportSlot[1], supportSlot[2]], traits: ["Armiger", "Flex Weapons", "Walking Armory"], limitbreak: "Cycle Weapons" },
  Assassin: { name: "Assassin", stats: { scope: 8, hp: 8, recoveries: 3, dodge: 11, speed: 6, stresscap: 5, memory: 6, adef: 7, mp: 2, saveTarget: 10 }, weapons: [weaponSlot[1], weaponSlot[21]], supports: [supportSlot[1], supportSlot[1], supportSlot[2]], traits: [], limitbreak: "Exterminate" },
  Berserker: { name: "Berserker", stats: { scope: 5, hp: 16, recoveries: 6, dodge: 8, speed: 6, stresscap: 6, memory: 4, adef: 6, mp: 1, saveTarget: 10 }, weapons: [weaponSlot[2], weaponSlot[3]], supports: [supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Primal Strike" },
  Chronomancer: { name: "Chronomancer", stats: { scope: 10, hp: 6, recoveries: 3, dodge: 7, speed: 5, stresscap: 6, memory: 6, adef: 9, mp: 5, saveTarget: 12 }, weapons: [weaponSlot[1], weaponSlot[1]], supports: [supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Time Shuffle" },
  DemonHunter: { name: "DemonHunter", stats: { scope: 8, hp: 10, recoveries: 4, dodge: 8, speed: 6, stresscap: 9, memory: 5, adef: 8, mp: 2, saveTarget: 10 }, weapons: [weaponSlot[1], weaponSlot[21]], supports: [supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Become the Monster" },
  Demonologist: { name: "Demonologist", stats: { scope: 12, hp: 7, recoveries: 2, dodge: 7, speed: 5, stresscap: 6, memory: 6, adef: 12, mp: 4, saveTarget: 11 }, weapons: [weaponSlot[2]], supports: [supportSlot[1], supportSlot[2]], traits: [], limitbreak: "Legion" },
  DragonRider: { name: "DragonRider", stats: { scope: 5, hp: 9, recoveries: 5, dodge: 7, speed: 6, stresscap: 4, memory: 5, adef: 7, mp: 3, saveTarget: 11 }, weapons: [weaponSlot[1], weaponSlot[2], weaponSlot[3]], supports: [supportSlot[2], supportSlot[2]], traits: [], limitbreak: "Dragon Echo" },
  Druid: { name: "Druid", stats: { scope: 10, hp: 9, recoveries: 4, dodge: 7, speed: 4, stresscap: 6, memory: 6, adef: 9, mp: 4, saveTarget: 11 }, weapons: [weaponSlot[1], weaponSlot[2]], supports: [supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Tempest Storm" },
  Equinox: { name: "Equinox", stats: { scope: 12, hp: 6, recoveries: 3, dodge: 6, speed: 4, stresscap: 5, memory: 7, adef: 10, mp: 5, saveTarget: 11 }, weapons: [weaponSlot[2]], supports: [supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Tetraflare" },
  Gravewalker: { name: "Gravewalker", stats: { scope: 10, hp: 8, recoveries: 6, dodge: 6, speed: 4, stresscap: 5, memory: 5, adef: 8, mp: 3, saveTarget: 10 }, weapons: [weaponSlot[2], weaponSlot[3]], supports: [supportSlot[2], supportSlot[3]], traits: [], limitbreak: "That Which is Already Dead" },
  Gunslinger: { name: "Gunslinger", stats: { scope: 8, hp: 8, recoveries: 3, dodge: 10, speed: 5, stresscap: 5, memory: 5, adef: 6, mp: 3, saveTarget: 11 }, weapons: [weaponSlot[11], weaponSlot[2], weaponSlot[3]], supports: [supportSlot[1], supportSlot[2]], traits: [], limitbreak: "Customized Ammo" },
  Hexblade: { name: "Hexblade", stats: { scope: 10, hp: 8, recoveries: 4, dodge: 7, speed: 5, stresscap: 5, memory: 6, adef: 8, mp: 4, saveTarget: 11 }, weapons: [weaponSlot[11], weaponSlot[2]], supports: [supportSlot[1], supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Doom Hex" },
  Knightmare: { name: "Knightmare", stats: { scope: 5, hp: 9, recoveries: 4, dodge: 6, speed: 6, stresscap: 6, memory: 5, adef: 7, mp: 3, saveTarget: 11 }, weapons: [weaponSlot[1], weaponSlot[2], weaponSlot[3]], supports: [supportSlot[2], supportSlot[3]], traits: [], limitbreak: "Trapped in a Dream" },
  Lifeweaver: { name: "Lifeweaver", stats: { scope: 12, hp: 6, recoveries: 10, dodge: 7, speed: 5, stresscap: 6, memory: 6, adef: 8, mp: 4, saveTarget: 10 }, weapons: [weaponSlot[2]], supports: [supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Second Life" },
  Paladin: { name: "Paladin", stats: { scope: 5, hp: 9, recoveries: 6, dodge: 6, speed: 5, stresscap: 7, memory: 5, adef: 7, mp: 2, saveTarget: 10 }, weapons: [weaponSlot[2], weaponSlot[3]], supports: [supportSlot[2], supportSlot[3]], traits: [], limitbreak: "Bastion of Resolve" },
  Phoenix: { name: "Phoenix", stats: { scope: 15, hp: 7, recoveries: 2, dodge: 6, speed: 4, stresscap: 7, memory: 6, adef: 10, mp: 5, saveTarget: 11 }, weapons: [weaponSlot[1], weaponSlot[2]], supports: [supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Supervolcano" },
  Riftblade: { name: "Riftblade", stats: { scope: 15, hp: 8, recoveries: 3, dodge: 7, speed: 4, stresscap: 5, memory: 6, adef: 8, mp: 4, saveTarget: 10 }, weapons: [weaponSlot[1], weaponSlot[3]], supports: [supportSlot[1], supportSlot[1], supportSlot[1], supportSlot[2]], traits: [], limitbreak: "Gateway" },
  Rimeguard: { name: "Rimeguard", stats: { scope: 8, hp: 1, recoveries: 5, dodge: 6, speed: 5, stresscap: 5, memory: 5, adef: 9, mp: 4, saveTarget: 11 }, weapons: [weaponSlot[2], weaponSlot[2]], supports: [supportSlot[2], supportSlot[3]], traits: [], limitbreak: "Absolute Zero" },
  Seeker: { name: "Seeker", stats: { scope: 20, hp: 6, recoveries: 3, dodge: 8, speed: 5, stresscap: 4, memory: 6, adef: 9, mp: 3, saveTarget: 11 }, weapons: [weaponSlot[2], weaponSlot[3]], supports: [supportSlot[1], supportSlot[2]], traits: [], limitbreak: "Heavenly Starfall" },
  Shadebinder: { name: "Shadebinder", stats: { scope: 10, hp: 6, recoveries: 5, dodge: 7, speed: 4, stresscap: 5, memory: 6, adef: 7, mp: 4, saveTarget: 12 }, weapons: [weaponSlot[1]], supports: [supportSlot[1], supportSlot[1], supportSlot[2], supportSlot[2]], traits: [], limitbreak: "Aetheric Evolution" },
  ShadowDancer: { name: "ShadowDancer", stats: { scope: 12, hp: 8, recoveries: 3, dodge: 12, speed: 7, stresscap: 4, memory: 5, adef: 7, mp: 4, saveTarget: 10 }, weapons: [weaponSlot[11]], supports: [supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Eclipse" },
  Shapeshifter: { name: "Shapeshifter", stats: { scope: 10, hp: 8, recoveries: 4, dodge: 8, speed: 5, stresscap: 7, memory: 5, adef: 7, mp: 4, saveTarget: 10 }, weapons: [weaponSlot[1], weaponSlot[3]], supports: [supportSlot[1], supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Perfect Form" },
  Skald: { name: "Skald", stats: { scope: 10, hp: 7, recoveries: 4, dodge: 8, speed: 5, stresscap: 6, memory: 6, adef: 9, mp: 4, saveTarget: 11 }, weapons: [weaponSlot[2]], supports: [supportSlot[1], supportSlot[2]], traits: [], limitbreak: "Ballad" },
  Thunderclaw: { name: "Thunderclaw", stats: { scope: 5, hp: 8, recoveries: 5, dodge: 10, speed: 6, stresscap: 5, memory: 6, adef: 7, mp: 2, saveTarget: 10 }, weapons: [weaponSlot[11], weaponSlot[2]], supports: [supportSlot[1], supportSlot[2]], traits: [], limitbreak: "Living Lightning" },
  Tidecaller: { name: "Tidecaller", stats: { scope: 8, hp: 8, recoveries: 3, dodge: 6, speed: 5, stresscap: 6, memory: 6, adef: 10, mp: 5, saveTarget: 12 }, weapons: [weaponSlot[1], weaponSlot[2]], supports: [supportSlot[1], supportSlot[1]], traits: [], limitbreak: "Tidal Wave" },
  Warden: { name: "Warden", stats: { scope: 5, hp: 12, recoveries: 6, dodge: 6, speed: 5, stresscap: 6, memory: 5, adef: 8, mp: 2, saveTarget: 10 }, weapons: [weaponSlot[2], weaponSlot[3]], supports: [supportSlot[1], supportSlot[1], supportSlot[2]], traits: [], limitbreak: "Gaia's Wrath" },
  Warlord: { name: "Warlord", stats: { scope: 12, hp: 10, recoveries: 5, dodge: 7, speed: 5, stresscap: 5, memory: 7, adef: 6, mp: 2, saveTarget: 10 }, weapons: [weaponSlot[2], weaponSlot[2]], supports: [supportSlot[1], supportSlot[1], supportSlot[2]], traits: [], limitbreak: "Follow My Lead" },
}

export const ancestriesData = {
  Avian: { name: "Avian", size: 1, traits: ["Flight", "Get the Flock Outta There", "Flock Tactics", "Gust"] },
  Cambion: { name: "Cambion", size: 1, traits: ['Bloodhunter', 'Infernal Resistance', 'Wrath', 'Fiendish Wings'] },
  Draken: { name: "Draken", size: 2, traits: ['Dragonfire', 'Dragon Scales', 'Inner Fire', 'Draconic Wings'] },
  Dwarf: { name: "Dwarf", size: 1, traits: ['Keep Moving Forward', 'Resilience', 'Unyielding', 'Sturdy'] },
  Elemental: { name: "Elemental", size: 1, traits: ['Energy Resistance', 'Energy Aura', 'Elemental Nova', 'Elemental Form'] },
  Elf: { name: "Elf", size: 1, traits: ['Elven Accuracy', 'Nature Step', 'Fast Movement', 'Fey Step'] },
  Gigan: { name: "Gigan", size: 2, traits: ['Big Equipment', 'Endure', 'Oversized Weapons', 'Giant Lineage'] },
  Gnome: { name: "Gnome", size: 1 / 2, traits: ['Instinctual Stealth', 'Fade Away', 'Tumble', 'Tinker Toy'] },
  Goblin: { name: "Goblin", size: 1 / 2, traits: ['Scurry', 'Swarm', 'Nimble Escape', 'Bite'] },
  Halfling: { name: "Halfling", size: 1 / 2, traits: ['Lucky', 'Nimble', 'Brave', 'Tumble'] },
  Human: { name: "Human", size: 1, traits: ['Strong Saves', 'Hang in There', 'Hearty', 'Adrenaline'] },
  Kobold: { name: "Kobold", size: 1 / 2, traits: ['Trap Array', 'Distract', 'Trapmaster', 'Evasive'] },
  Lycanthrope: { name: "Lycanthrope", size: 1, traits: ['Defender Strain', 'Pack Tactics', 'Sneaky Form', 'Travel Form'] },
  Machina: { name: "Machina", size: 1, traits: ['Mechanical Body', 'Armored', 'System Repair', 'Integrated Weapon'] },
  Orc: { name: "Orc", size: 2, traits: ['Second Wind', 'Rushdown', 'Furious', 'Work Out Routine'] },
}

const jobTraitActions = {
  "Demon Form": { name: "Demon Form", type: "Action", actionType: "Free Action", tags: ["Polymorph"] },
  "Infernal Aether": { name: "Infernal Aether", type: "Action", actionType: "Minor Action", tags: ["Stressful X"] },
  "Demon Lexicon": { name: "Demon Lexicon", type: "Action", actionType: "(3) Volley", tags: ["Mana 2", "Summon"], range: "Scope" },
  "Sacrifice": { name: "Sacrifice", type: "Action", actionType: "Minor Action", tags: [], range: "Scope" },
  "Skythrust": { name: "Skythrust", type: "Action", actionType: "Minor Action", tags: ["Stressful 1"] },
  "Tombstone": { name: "Tombstone", type: "Action", actionType: "Minor Action", tags: ["Mana 1, Summon"], range:"Scope" },
  "Purge Malady": { name: "Purge Malady", type: "Action", actionType: "Minor Action", tags: ["Mana 2"], range:"Scope" },
  "Quick Stitch": { name: "Quick Stitch", type: "Action", actionType: "Reaction", tags: ["Mana 1"] },
  "Guardian Angel": { name: "Guardian Angel", type: "Action", actionType: "Minor Action", tags: [] },
  "Rift": { name: "Rift", type: "Action", actionType: "Minor Action", tags: ["Mana 1"], range:"20" },
  "Frost Armor": { name: "Frost Armor", type: "Action", actionType: "Minor Action", tags: ["Focus 1"], range:"Scope" },
  "Rimeheart": { name: "Rimeheart", type: "Action", actionType: "Minor Action", tags: [], range:"Scope" },
  "Seeker's Sight": { name: "Seeker's Sight", type: "Action", actionType: "Minor Action", tags: ["Mana 1"] },
  "Companion Shade": { name: "Companion Shade", type: "Action", actionType: "Minor Action", tags: ["Summon"], range:"Scope" },
  "Inspire": { name: "Inspire", type: "Action", actionType: "Free Action", tags: ["Mana 1", "1/turn"], range:"Scope" },
  "Fast as Lightning": { name: "Fast as Lightning", type: "Action", actionType: "Minor Action", tags: ["Mana 1"] },
  "River Current": { name: "River Current", type: "Action", actionType: "Minor Action", tags: ["Mana 1"], range:"Scope, Line 6" },
  "Water Veil": { name: "Water Veil", type: "Action", actionType: "Reaction", tags: ["Mana 1"] },
}

export const jobTraitsData = {
  "Abjurer's Ward": { name: "Abjurer's Ward", type: "trait", unlockedActions: ["Ward"], effect: "You gain the Ward spell, which is equipped for free." },
  "Mana Transferral": { name: "Mana Transferral", type: "trait", unlockedActions: [], effect: "You can spend MP as if it were Focus." },
  "Potion Belt": { name: "Potion Belt", type: "trait", unlockedActions: [], effect: "Your Consumable abilities each gain +1 Consumable. Additionally, during Short Rests, you can regain all charges for Consumable abilities at a cost of 1 Recovery per ability." },
  "Potion Injector": { name: "Potion Injector", type: "trait", unlockedActions: [], effect: `Your Consumable abilities can be used up to Range 8, and effects that would usually only apply to yourself (like Healing Potions, p. 218) can be used on willing allies within that Range.\n *Standard Action: During Phase Skirmish or later, you use a support item that would normally require a minor action.` },
  "Sanitizing Vapors": { name: "Sanitizing Vapors", type: "trait", unlockedActions: [], effect: "At the end of your turn, an ally within Range 3 can clear 1 Stress, or up to 2 Stress if they are Breaking." },
  "Armiger": { name: "Armiger", type: "trait", unlockedActions: ["Phantom Armory"], effect: "You gain the Phantom Armory weapon, which is equipped for free." },
  "Flex Weapons": { name: "Flex Weapons", type: "trait", unlockedActions: [], effect: "You can choose to treat your Main weapon slots as [Light/Light] slots, and your Heavy slots as [Main/Light] slots." },
  "Walking Armory": { name: "Walking Armory", type: "trait", unlockedActions: [], effect: "When you Refresh, you can spend 1 MP to repair one of your destroyed weapons or support items. During a Short Rest, you can repair one weapon and one support item for free." },
  "Assassinate": { name: "Assassinate", type: "trait", unlockedActions: [], effect: "1/round, you may deal +1d6 bonus damage on a hit with a melee attack if you are Hidden or if you are the only character adjacent to the target." },
  "Preparation": { name: "Preparation", type: "trait", unlockedActions: [], effect: "At the end of each of your turns while Hidden, you gain 1 Prep, to a maximum of 6. After making an attack roll, you can decide to spend any amount of Prep, adding +1 to the attack roll per Prep. Prep lasts for the rest of the scene or until spent" },
  "Endless Endurance": { name: "Endless Endurance", type: "trait", unlockedActions: [], effect: "Removing a Wound or Overstress during a Short Rest only costs you 1 Recovery." },
  "Reckless": { name: "Reckless", type: "trait", unlockedActions: [], effect: "1/round, you may deal +1d6 bonus damage on a hit with a melee attack. If you do so, attacks against you gain +1 until the end of your next turn." },
  "Relentless": { name: "Relentless", type: "trait", unlockedActions: [], effect: "1/round when you critically hit, you can make an additional attack with the same ability." },
  "Pluck the Threads of Time": { name: "Pluck the Threads of Time", type: "trait", unlockedActions: [], effect: "" },
  "Undo": { name: "Undo", type: "trait", unlockedActions: [], effect: "" },
  "Corruption": { name: "Corruption", type: "trait", unlockedActions: [], effect: "" },
  "Demon Form": { name: "Demon Form", type: "trait", unlockedActions: [], effect: "" },
  "Infernal Aether": { name: "Infernal Aether", type: "trait", unlockedActions: [], effect: "" },
  "Demon Lexicon": { name: "Demon Lexicon", type: "trait", unlockedActions: [], effect: "" },
  "Sacrifice": { name: "Sacrifice", type: "trait", unlockedActions: [], effect: "" },
  "Forceful Jab": { name: "Forceful Jab", type: "trait", unlockedActions: [], effect: "" },
  "Skyhunter": { name: "Skyhunter", type: "trait", unlockedActions: [], effect: "" },
  "Skythrust": { name: "Skythrust", type: "trait", unlockedActions: [], effect: "" },
  "Briar Patch": { name: "Briar Patch", type: "trait", unlockedActions: [], effect: "" },
  "Nature's Path": { name: "Nature's Path", type: "trait", unlockedActions: [], effect: "" },
  "Root": { name: "Root", type: "trait", unlockedActions: [], effect: "" },
  "Day/Night Cycle": { name: "Day/Night Cycle", type: "trait", unlockedActions: [], effect: "" },
  "Mage Tower": { name: "Mage Tower", type: "trait", unlockedActions: [], effect: "" },
  "Tombstone": { name: "Tombstone", type: "trait", unlockedActions: [], effect: "" },
  "Harvest": { name: "Harvest", type: "trait", unlockedActions: [], effect: "" },
  "Written Name": { name: "Written Name", type: "trait", unlockedActions: [], effect: "" },
  "Fast Reload": { name: "Fast Reload", type: "trait", unlockedActions: [], effect: "" },
  "Stare Down": { name: "Stare Down", type: "trait", unlockedActions: [], effect: "" },
  "Hex": { name: "Hex", type: "trait", unlockedActions: [], effect: "" },
  "Misery": { name: "Misery", type: "trait", unlockedActions: [], effect: "" },
  "The Chains of Despair": { name: "The Chains of Despair", type: "trait", unlockedActions: [], effect: "" },
  "The Inescapable Nightmare": { name: "The Inescapable Nightmare", type: "trait", unlockedActions: [], effect: "" },
  "The Weight of Inevitability": { name: "The Weight of Inevitability", type: "trait", unlockedActions: [], effect: "" },
  "Purge Malady": { name: "Purge Malady", type: "trait", unlockedActions: [], effect: "" },
  "Healer's Burden": { name: "Healer's Burden", type: "trait", unlockedActions: [], effect: "" },
  "Quick Stitch": { name: "Quick Stitch", type: "trait", unlockedActions: [], effect: "" },
  "Guardian Angel": { name: "Guardian Angel", type: "trait", unlockedActions: [], effect: "" },
  "Layered Auras": { name: "Layered Auras", type: "trait", unlockedActions: [], effect: "" },
  "Retribution": { name: "Retribution", type: "trait", unlockedActions: [], effect: "" },
  "Burn Proof": { name: "Burn Proof", type: "trait", unlockedActions: [], effect: "" },
  "Burning Spells": { name: "Burning Spells", type: "trait", unlockedActions: [], effect: "" },
  "Rift": { name: "Rift", type: "trait", unlockedActions: [], effect: "" },
  "Riftcutter": { name: "Riftcutter", type: "trait", unlockedActions: [], effect: "" },
  "Frost Armor": { name: "Frost Armor", type: "trait", unlockedActions: [], effect: "" },
  "Rimeheart": { name: "Rimeheart", type: "trait", unlockedActions: [], effect: "" },
  "Icy Veins": { name: "Icy Veins", type: "trait", unlockedActions: [], effect: "" },
  "Guided Shot": { name: "Guided Shot", type: "trait", unlockedActions: [], effect: "" },
  "Marksman's Eye": { name: "Marksman's Eye", type: "trait", unlockedActions: [], effect: "" },
  "Seeker's Sight": { name: "Seeker's Sight", type: "trait", unlockedActions: [], effect: "" },
  "Companion Shade": { name: "Companion Shade", type: "trait", unlockedActions: [], effect: "" },
  "Command Partner": { name: "Command Partner", type: "trait", unlockedActions: [], effect: "" },
  "Shadow Clones": { name: "Shadow Clones", type: "trait", unlockedActions: [], effect: "" },
  "Shadow Realm": { name: "Shadow Realm", type: "trait", unlockedActions: [], effect: "" },
  "Slip Step": { name: "Slip Step", type: "trait", unlockedActions: [], effect: "" },
  "Beast Weapons": { name: "Beast Weapons", type: "trait", unlockedActions: [], effect: "" },
  "Form for the Occasion": { name: "Form for the Occasion", type: "trait", unlockedActions: [], effect: "" },
  "Soothe": { name: "Soothe", type: "trait", unlockedActions: [], effect: "" },
  "Inspire": { name: "Inspire", type: "trait", unlockedActions: [], effect: "" },
  "Encore": { name: "Encore", type: "trait", unlockedActions: [], effect: "" },
  "Tempo": { name: "Tempo", type: "trait", unlockedActions: [], effect: "" },
  "Balance": { name: "Balance", type: "trait", unlockedActions: [], effect: "" },
  "Fast as Lightning": { name: "Fast as Lightning", type: "trait", unlockedActions: [], effect: "" },
  "Flurry": { name: "Flurry", type: "trait", unlockedActions: [], effect: "" },
  "River Current": { name: "River Current", type: "trait", unlockedActions: [], effect: "" },
  "Rising Tide": { name: "Rising Tide", type: "trait", unlockedActions: [], effect: "" },
  "Water Veil": { name: "Water Veil", type: "trait", unlockedActions: [], effect: "" },
  "Earthen Slide": { name: "Earthen Slide", type: "trait", unlockedActions: [], effect: "" },
  "Grasping Vines": { name: "Grasping Vines", type: "trait", unlockedActions: [], effect: "" },
  "Focused Plan": { name: "Focused Plan", type: "trait", unlockedActions: [], effect: "" },
  "Take a Breather": { name: "Take a Breather", type: "trait", unlockedActions: [], effect: "" },
}
